language: python
os: linux

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python -V
  - pylint --load-plugins pylint_django --disable=missing-docstring ./whattowatch/whattowatch
    # Run tests
  - coverage run --source=whattowatch manage.py test

# after_success:
#   coveralls
